### ISSUE TITLE
Speed up travis-ci

### ISSUE THREAD

**Issue by franchoco** [niclabs/tchsm-libdtc#26]
Nowadays our travis-ci script takes ~7 minutes.

**Comment by fmontoto** [comment]
The BOTAN version of Ubuntu 14.04 does not work with the code, and there is no binary distribution at the page so we have to compile it each time. This compilation process is taking too long. A possible solution would be to compile it and store the binary somewhere, then each time we want to run a test we can grab it from there.

**Comment by franchoco** [comment]
Ok, I will try to provide a binary Botan version from a http server I have access.

**Comment by franchoco** [comment]
RFC: There is another possibility: using a container-based (docker) travis environment instead of a full VM. With this, we may use another base-distro.

**Comment by fmontoto** [comment]
Check if this help us and provide the necessary features, if so change the .travis file to use docker.

**Comment by franchoco** [comment]
The container-based travis environment uses Ubuntu 12.04, and that's too old for our project. The only  benefit is the cache between instructions. 
The cleanest way to do this is creating ubuntu packages and creating a PPA.
As this have a low priority, I will tag it as an idea.

**Comment by franchoco** [comment]
Precompiling Botan gives us a speed up, but that's not enough. We might try precompiling Libsodium and ZeroMQ too. I will do a pull request for the current setup, but I won't close the issue.

**Comment by fmontoto** [comment]
The server with the Botan's binaries died. I'm removing the tag idea to this issue as our test are taking 10 minutes again and we have a solution, we just need a server to store and serve the files.

**Comment by fmontoto** [comment]
Can we get a server @madestro ?

**Comment by madestro** [comment]
yes

**Comment by franchoco** [comment]
http://200.7.6.140:8080/botan-1.11-ubuntu-14.04.tar.gz

**Comment by fmontoto** [comment]
#48 Introduces the compiled botan again. I'll leave this open as we still have too large testing times due the compiling of the other dependencies. We should do the same we did with botan with the other dependencies.
