### ISSUE TITLE
Move basic pkcs11 tests from src to tests

### ISSUE THREAD

**Issue by franchoco** [niclabs/tchsm-libdtc#27]
- [x] Move botanmain.
- [x] Move pkcs11_test

**Comment by DanielAviv** [comment]
Done in the SystemTest branch

**Comment by fmontoto** [comment]
You can use this https://github.com/blog/1506-closing-issues-via-pull-requests to close the issue when you send the pull request.

**Comment by fmontoto** [comment]
#53 is still under review, this isn't fixed.
