### ISSUE TITLE
Make the test pass and run some at travis

### ISSUE THREAD

**Issue by fmontoto** [niclabs/tchsm-libdtc#91]
System tests are still not passing and some of them even behaving in a non deterministic way. Check and fix it.

**Comment by fmontoto** [comment]
There is a bug I'm tracking. PKCS11 test is failing at verify randomly.

**Comment by fmontoto** [comment]
It looks like pycrypto has a [bug] (openssl dgst -sha256 -sigopt rsa_padding_mode:pss -sign ~/openssl_test/privateKey.kry -out ~/openssl_test/signed_openssl /tmp/libdtc_test_18/to_sign.txt)  at pss verification. As the project is no longer supported we're going to change it to py openssl an open ssl wrapper. The command in openssl to verify the signature is:
`openssl dgst -sha256 -sigopt rsa_padding_mode:pss -verify <publickey.pem> -signature <binary_signature_file <original_file>`

**Comment by raticate** [comment]
Fixed bug using openssl via subprocess.Popen. 
pycrypto is still being used to construct the public key.
